---
title: "Statistical Inference course project: part 2"
author: "Evgeny Petrovskiy"
date: '2017-10-21'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

load ToothGrowth dataset
```{r load}
data("ToothGrowth")
tg <- ToothGrowth
```

display data 
```{r plot}
gg <- ggplot(data = tg, aes(x = supp, y = len, color = supp)) +
  #geom_point(shape = 1) + 
  geom_boxplot() +
  #geom_jitter() +
  facet_grid(. ~ dose)
gg
```

summary of data
```{r summary}
summary(tg)
```

get VC values for each dose
```{r}
vc05 <- subset(tg, tg$sup == "VC" & tg$dose == 0.5)$len
vc10 <- subset(tg, tg$sup == "VC" & tg$dose == 1.0)$len
vc20 <- subset(tg, tg$sup == "VC" & tg$dose == 2.0)$len
oj05 <- subset(tg, tg$sup == "OJ" & tg$dose == 0.5)$len
oj10 <- subset(tg, tg$sup == "OJ" & tg$dose == 1.0)$len
oj20 <- subset(tg, tg$sup == "OJ" & tg$dose == 2.0)$len

```

say that vc10 gives bigger len than vc05

say that oj05 is more effective than vc05